---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - "${{ github.event.repository.default_branch }}"

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          DEFAULT_BRANCH: "${{ github.event.repository.default_branch }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          YAML_CONFIG_FILE: .yamllint.yaml
